events {
    worker_connections 1024;
}

http {
    server {
        listen 8000;

        # Route User Service Requests
        location /user-service/ {
            proxy_pass http://user-service:5000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route Author Service Requests
        location /author-service/ {
            proxy_pass http://author-service:5001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Route Blog Service Requests
        location /blog-service/ {
            proxy_pass http://blog-service:5002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}